namespace: "softasap"
name: "secure_box"
description: Installs set of security tools over your box
version: "0.0.1"
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
    - lynis
    - debsums
    - hardening
repository: "https://github.com/oops-to-devops/secure_box.git"
documentation: "https://github.com/oops-to-devops/secure_box/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
